name: api_request_testing
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.6.0
  fluttertoast: ^8.2.4
  sign_in_button: ^3.2.0
  flutter_webrtc: ^0.9.47
  url_strategy: ^0.2.0
  socket_io_client: ^2.0.3+1
  stomp_dart_client: ^1.0.2
  video_player: ^2.8.2
  camera: ^0.10.5+9
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.10
  swipable_stack: ^2.0.0
  http: ^1.2.0
  auto_animated: ^3.2.0
  smooth_page_indicator: ^1.1.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
